name       : python-inotify
version    : 0.9.6
release    : 4
source     :
    - https://pypi.python.org/packages/e3/c0/fd5b18dde17c1249658521f69598f3252f11d9d7a980c5be8619970646e1/pyinotify-0.9.6.tar.gz : 9c998a5d7606ca835065cdabc013ae6c66eb9ea76a00a1e3bc6e0cfe2b4f71f4
license    : GPL-2.0
component  : programming.python
summary    : An adapter to Linux kernel support for inotify directory-watching.
description: |
    An adapter to Linux kernel support for inotify directory-watching.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
