name       : python-inotify
version    : 0.2.8
release    : 1
source     :
    - https://pypi.python.org/packages/ab/3b/ad48cb45af4af32341fc6bf28497081a885d1e23777d2827f3c61d734f02/inotify-0.2.8.tar.gz : 837638060997c2c1a87c015f56479f0e05d8403a47c6fe729aacd3746b885fe9
license    : GPL-2.0
component  : programming.python
summary    : An adapter to Linux kernel support for inotify directory-watching.
description: |
    An adapter to Linux kernel support for inotify directory-watching.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
